language: csharp
solution: Source/ConsoleReader.sln
install:
  - nuget restore Source/ConsoleReader.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Source/ConsoleReader.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe .\Source\Console.Reader.DependencyInjection.UnitTests\bin\Release\Console.Reader.DependencyInjection.UnitTests.dll